# Site settings
title: Sriharsha | Aerospace Engineer
tag_text: About Sriharsha Sheshanarayana
description: This is a short about me page of Sriharsha Sheshanarayana

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
twitter_username:     sriharsha_space
